services:
  xampp:
    image: tomsik68/xampp:8
    platform: linux/amd64
    ports:
      - 80:80
      - 3306:3306
      - 8443:443
      - 22:22
    volumes:
      - ./www:/opt/lampp/htdocs
      - mysql_data:/opt/lampp/var/mysql
    working_dir: /opt/lampp/htdocs
    command: sh -c "curl -ksSL https://github.com/composer/composer/releases/latest/download/composer.phar -o /usr/local/bin/composer && chmod +x /usr/local/bin/composer && ln -sf /opt/lampp/bin/php /usr/local/bin/php && /opt/lampp/lampp start && sleep infinity"

volumes:
  mysql_data:
