services:
  xampp:
    image: tomsik68/xampp:8
    ports:
      - 80:80
      - 3306:3306
      - 8443:443
      - 22:22
    volumes:
      - ./www:/opt/lampp/htdocs
      - mysql_data:/opt/lampp/var/mysql
    # command: sh -c "curl -ksS https://getcomposer.org/installer | /opt/lampp/bin/php -- --install-dir=/usr/local/bin --filename=composer && ln -s /opt/lampp/bin/php /usr/local/bin/php && /opt/lampp/lampp start && sleep infinity"

volumes:
  mysql_data:
